declare module 'color-thief'
declare module 'colorthief'
declare module 'rgbaster'
declare module 'element-plus'
declare module '@kangc/v-md-editor/lib/preview'
declare module '@kangc/v-md-editor/lib/theme/github.js'
declare module 'highlight.js'
declare module 'IntersectionObserver'
